# -*- coding: utf-8 -*-
"""praw

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BJoSuaa7Ii27F3Ih-dCom229yKIpBWKr
"""

!pip install praw 
!pip install pandas

import praw
import re
import pandas as pd

reddit = praw.Reddit(client_id='', client_secret='', user_agent='',username = "",     
                     password = "")

query =  ["Bombat", "Tullaga Tunni", "Hadshee Magane", "Nimmoun Tull", "Chooth Maarike", "Chooth Maarike", "TUNNE UNNU", "Tika keisko", 
          "Dengsko", "choolu" , "Nalle", "Mahiḷeyaru" , "Huḍugi", "Mādaka mahiḷeyaru" , "Has'si", "Bāliśa", "Strīvādi", 
          "en maal guru", "nimmoun hadshike", "hadasbeda" , "chodimagalu", "tika mucchu", "sule magalu", "randi magalu", 
          "hadaragitti", "hadiba", "huchhadshike", "haphadshike", "hapusulemagalu", "Bolimagalu", "chinalimagalu", 
          "choothmarike" , "tayina hada", "shantagtunni", "shraddha", "nadi haditeni", "bandu tunni nekku", 
          "hadbitti", "high mandri", "moole madhya tunni kaisi", "tika haditini","women","lady"]

posts = {"Code":[],"Body":[],"title":[],"comment_num":[],"created":[]}
for m in query:
    for submission in reddit.subreddit("IndianCinemaRegional").search(m, sort="top", limit=100):
        posts["Code"].append(submission.id)
        posts["Body"].append(submission.permalink)
        posts["title"].append(submission.title)
        posts["comment_num"].append(submission.num_comments)
        posts["created"].append(submission.created)

posts

df= pd.DataFrame(posts) 
df.to_csv('IndianCinemaRegional_redcomminfo.csv')

comments_dict = {
    "id":[],
    "comment_id": [],
    "comment_link_id": [],
     "comment_body" : [],
}

for i in posts["Code"]:
    submission = reddit.submission(i)
    submission.comments.replace_more(limit=None)
    comment_queue = submission.comments[:]  # Seed with top-level
    while comment_queue:
        comment = comment_queue.pop(0)
        comments_dict["id"].append(i)
        comments_dict["comment_id"].append(comment.id)
        comments_dict["comment_link_id"].append(comment.link_id)
        comments_dict["comment_body"].append(comment.body)
        comment_queue.extend(comment.replies)

df1 = pd.DataFrame(comments_dict) 
    
df1.to_csv('IndianCinemaRegional.csv')

